databases:
  - name: goodfellow-db
    plan: free
    databaseName: resource_locator_db
    user: resource_locator_user

services:
  - type: web
    plan: free
    name: goodfellow-resource-locator
    runtime: python
    rootDir: resource_locator_mvp
    buildCommand: ./build.sh
    startCommand: >
      python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goodfellow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: '4'
      - key: GOOGLE_API_KEY
        sync: false